
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  #fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0

mysql:
  database: webpanel-core
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null
  - mysql -e "create database IF NOT EXISTS testing;" -uroot

install:
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # add composer's global bin directory to the path
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  - cd ../..
  - composer install

script: phpunit